Update requirements.txt upgrade Pillow as it is required for Home Assistant
INFO: pip is looking at multiple versions of pixoo to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install pixoo==0.8.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    pixoo 0.8.3 depends on Pillow~=10.0.0
    The user requested (constraint) pillow==10.2.0